services:
  backend:
    build:
      context: "./Back End"
      dockerfile: Dockerfile
    container_name: apnaride-backend
    environment:
      SERVER_PORT: 9031
      DB_HOST: database-1.cc38e2ug2u3c.us-east-1.rds.amazonaws.com
      DB_PORT: 3306
      DB_NAME: apnaride
      DB_USERNAME: admin
      DB_PASSWORD: 12345678
      JPA_DDL_AUTO: update
      JPA_SHOW_SQL: "true"
      CORS_ALLOWED_ORIGINS: http://3.92.164.17:5173,http://3.92.164.17,http://localhost:5173
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "9031:9031"

  frontend:
    build:
      context: "./apnaride-frontend"
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: /api
        VITE_WS_BASE: /ws
    container_name: apnaride-frontend
    ports:
      - "5173:80"
